---
title: Olimpíadas Científicas
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  equipe:
    title: equipe
    output: true
email: your-email@domain.com
description: 'Informações sobre as principais Olimpíadas Científicas. OBM, OBQ, OBA,
  OBF, OBL, ONHB, OBG, IYPT, IJSO, OBI, OBB, OBQJr, IPhO, IOAA, IMO, IOL, IChO, IBO

'
info: Este site não tem qualquer ligação com a organização oficial das olimpíadas
  aqui divulgadas. Partes técnicas relativas a inscrições, resultados individuais
  e afins devem ser tratadas diretamente com os organizadores das olimpíadas.
copyright: "© 2016  Olimpíadas Científicas. Todos os direitos reservados."
baseurl: ''
mediaurl: "/static/"
url: http://olimpiadascientificas.org
twitter_username: OCientificas
github_username: OlimpiadasCientificas/olimpiadascientificas.github.io
disqus-shortname: olimpiadascientificas-com
markdown: kramdown
auto-menu: false
compress_html:
  blanklines: false
kramdown:
  input: GFM
  hard_wrap: false
excerpt_separator: "<!--more-->"
permalink: "/:year/:month/:day/:title/"
paginate: 10
prose:
  rooturl: ''
  siteurl: http://olimpiadascientificas.github.io/
  media: static/images
plugins:
- jekyll-redirect-from
- jekyll-paginate
